### PR TITLE
Fix PED bug-report mismatches in help, usage, and email validation.

### LINKED ISSUE #261: [PE-D][Tester D] Edit command does not specify that new tag can be created
Refer to help text:
Image

Command help text does not specify that `-newtag` can be used with it. But is shown inside the user guide, so I believe it should be reflected in here too.

-------------
Labels: `severity.VeryLow` `type.DocumentationBug`

### LINKED ISSUE #274: [PE-D][Tester E] Consecutive special characters in email are considered invalid
`edit 1 e/a+a-a@example.com`: Is accepted
`edit 1 e/a+-a@example.com`: Causes invalid format message

Image

Any otherwise valid email with special characters (+_.-) that are **side-by-side** is considered invalid in the app.

This behaviour is not reflected in the message format, which says: 

> 1. The local-part should only contain alphanumeric characters and these special characters, excluding the parentheses, (+_.-). The local-part may not start or end with any special characters.

-------------
Labels: `severity.Low` `type.FunctionalityBug`

### PR DESCRIPTION
**Pull request by athrv2**
This aligns in-app guidance with the User Guide by linking directly to `UserGuide.html` and documenting `edit`'s `-newtag` flag, and it updates email parsing to allow consecutive local-part special characters as described.

## Summary

Fixes three PED-reported inconsistencies between documented behavior and app behavior/messages for Help URL navigation, `edit` usage guidance, and email validation.

Closes #261  
Closes #274

## Description of Changes

- **Help window URL fix**
  - Updated `HelpWindow.USERGUIDE_URL` to point directly to:
    - `https://ay2526s2-cs2103t-t10-2.github.io/tp/UserGuide.html`
  - This ensures the Help popup and copy-to-clipboard URL match the intended UG page.

- **`edit` command error/help text fix**
  - Updated `EditCommand.MESSAGE_USAGE` so invalid-format guidance now includes optional `[-newtag]`.
  - This aligns parser error output with documented `edit` functionality.

- **Email validation behavior fix**
  - Adjusted local-part regex in `Email` to allow consecutive special characters (e.g. `a+-a@example.com`, `a++a@example.com`) while preserving existing start/end restrictions.
  - Added/updated `EmailTest` assertions to cover the corrected behavior.

## Checklist

- [x] Tests have been added for the changes made.
- [x] Documentation has been updated where applicable, including docstrings for API changes. (UG, DG, portfolio, docstrings)
- [ ] Code follows the style guidelines of this project (run `./gradlew check` to verify).

### CODE REVIEW

File: src/main/java/seedu/address/ui/HelpWindow.java [hunk 1]
```diff
@@ -15,7 +15,7 @@
  */
 public class HelpWindow extends UiPart<Stage> {
 
-    public static final String USERGUIDE_URL = "https://ay2526s2-cs2103t-t10-2.github.io/tp/";
+    public static final String USERGUIDE_URL = "https://ay2526s2-cs2103t-t10-2.github.io/tp/UserGuide.html";
```
Comment (lamemario) [inline src/main/java/seedu/address/ui/HelpWindow.java:18]: Nice fix! This aligns the in-app Help link with the actual hosted UG page and avoids navigation mismatch.

File: src/main/java/seedu/address/logic/commands/EditCommand.java [hunk 2]
```diff
@@ -44,7 +44,8 @@ public class EditCommand extends Command {
             + "[" + PREFIX_PHONE + "PHONE] "
             + "[" + PREFIX_EMAIL + "EMAIL] "
             + "[" + PREFIX_ROOM + "ROOM] "
-            + "[" + PREFIX_TAG + "TAG]...\n"
+            + "[" + PREFIX_TAG + "TAG]... "
+            + "[" + PREFIX_NEWTAG + "]\n"
```
Comment (lamemario) [inline src/main/java/seedu/address/logic/commands/EditCommand.java:48]: Good sync with parser behavior; this prevents misleading guidance in invalid-format errors

File: src/main/java/seedu/address/model/person/Email.java [hunk 3]
```diff
@@ -26,8 +26,8 @@ public class Email {
             + "    - have each domain label consist of alphanumeric characters, separated only by hyphens, if any.";
     // alphanumeric and special characters
     private static final String ALPHANUMERIC_NO_UNDERSCORE = "[^\\W_]+"; // alphanumeric characters except underscore
-    private static final String LOCAL_PART_REGEX = "^" + ALPHANUMERIC_NO_UNDERSCORE + "([" + SPECIAL_CHARACTERS + "]"
-            + ALPHANUMERIC_NO_UNDERSCORE + ")*";
+    private static final String LOCAL_PART_REGEX = "^" + ALPHANUMERIC_NO_UNDERSCORE
+            + "([" + SPECIAL_CHARACTERS + "]*" + ALPHANUMERIC_NO_UNDERSCORE + ")*";
```
Comment (lamemario) [inline src/main/java/seedu/address/model/person/Email.java:30]: This regex update matches the documented email rules while preserving start/end constraints, great stuff!

**Review by lamemario — APPROVED** [review]
This PR brings Help URL, edit usage guidance, and email validation behavior back in sync with documentation, with targeted tests to lock in the expected behavior. Great stuff!
